//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaKayıtProgramı
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanisanMuayeneTablosu
    {
        public int Id { get; set; }
        public string TcKimlikNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Cinsiyet { get; set; }
        public byte Yas { get; set; }
        public string DanismanAdi { get; set; }
        public string DanismanSoyadi { get; set; }
        public System.DateTime MuayeneTarihi { get; set; }
        public string MuayeneSaati { get; set; }
        public string MuayeneSonucları { get; set; }
    }
}
